# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Metadata verifier

on:
  push:
    branches: [ main, tooling/challenge-metadata-verifier ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Check out verifier repo
      uses: actions/checkout@v2
      with:
        repository: 'BCACTF/challenge-metadata-verifier'
        path: 'challenge-metadata-verifier'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r challenge-metadata-verifier/requirements.txt
    - name: Verify challenge metadata
      run: |
        python challenge-metadata-verifier/ci.py
